### ISSUE TITLE
Build Typeahead component using new affiliation schema

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmsp_frontend_prototype#78] opened 2024-08-05 16:22 UTC
- Add it to style guide if possible

**Comment by jupiter007** [comment] 2024-08-05 16:23
Ask Adam Buttrick about his experience with typeahead

**Comment by bofstein** [comment] 2024-08-07 16:14
Closing as dupe of https://github.com/CDLUC3/dmsp_frontend_prototype/issues/10

**Closed by bofstein** 2024-08-07 16:14 UTC
